time: 5
announcements:
- 'Welcome to Eden!'
- 'Wyatt sucks'
- 'Kill DiamondDan_'
- 'This server is nonexistent'
- 'Is this the red pill...?'
- 'Or the blue pill...?'
- 'It's all In your head'
- 'The cake is a lie!'