name: Eden
main: Eden.Eden
version: 1.0

commands:
  killdan:
    usage: /killdan
    description: Kills DiamondDan_ whenever you please.
  flysean:
    usage: /flysean
    description: Makes Icecrest fly.
  tpr:
    usage: /tpr
    description: Teleport to a random location.
  banlist:
    usage: /banslist
    description: Prints the entire ban list to the console.
  testeden:
    usage: /testeden
    description: Tests to see if the command runner is working.