name: Eden
version: 1.8.11
main: Eden.Eden

commands:
   killdan:
      usage: /killdan
      description: Kills DiamondDan_ whenever you please.
   flysean:
      usage: /flysean
      description: Makes Icecrest fly.
   tpr:
      usage: /tpr
      description: Teleport to a random location.
   banlist:
      usage: /banlist
      description: Prints the entire ban list to the console.
   testeden:
      usage: /testeden
      description: Tests to see if the command runner is working.
   testplayer:
      usage: /testplayer [PLAYERNAME]
      description: Tests for a player name and prints if they are online or not.
   smite:
      usage: /smite [PLAYERNAME]
      description: Smites down your foes in glory!
   playgod:
    usage: /playgod
    description: Makes you look invincible.
   showinv:
      usage: /showinv [PLAYERNAME]
      description: Shows the inventory of a certain player.
   smitestick:
      usage: /smitestick
      description: Gives you the SmiteStick
   create:
      usage: /create [WEAPON][ENCHANTMENT][LEVEL]
      description: Creates a custom weapon.
   seteffect:
      usage: /seteffect [EFFECT]
      description: Adds an effect to a player's walking animation.
   enchant:
      usage: /enchant [ENCHANTMENT] [LEVEL]
      description: Adds an enchantment to the player's item.