name: Commander
main:Commander.CurlyFry
version: 1.0

commands:
    killdan:
        usage: /killdan
        description: Kills DiamondDan_ whenever you please.
    flysean:
        description: Makes Icecrest fly.
    tpr:
        description: Teleport to a random location.
